In [5]:
import numpy as np

In [2]:
l=[1,2,3,4]
np.mean[l]

TypeError: 'function' object is not subscriptable

In [3]:
np.mean(l)

2.5

In [6]:
np.array(l)

array([1, 2, 3, 4])

In [7]:
arr1=[[1,2,3],[4,5,6],[7,8,9]]
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(10,19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [11]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.rand(10)

array([0.47187474, 0.5674011 , 0.82908717, 0.6602667 , 0.67061086,
       0.38846457, 0.86330749, 0.83355967, 0.49157182, 0.56848319])

In [35]:
np.random.randn(5,5)

array([[-0.92798064,  0.18742346, -2.4569308 , -1.75055181, -1.5512076 ],
       [ 1.46516874,  0.26517823,  1.14853954,  0.31555256, -0.87026354],
       [-0.21713381, -0.22794724,  1.34482299,  1.40031432, -3.01335154],
       [ 0.54305156,  0.5053879 , -0.23896521, -1.41771679,  0.46134844],
       [ 0.4129977 ,  0.91954952,  0.40058759,  0.20315251, -1.09864386]])

In [36]:
np.random.randint(10)

6

In [39]:
np.random.randint(100)

37

In [58]:
np.random.randint(1,50,10)

array([45, 31, 35, 25, 12,  9, 18, 10, 20, 49])

array([0, 1, 2, 3, 4])

In [48]:
ranarr = np.random.randint(0,50,10)

In [49]:
ranarr

array([42, 14, 15,  7, 39, 49, 29, 21,  7, 39])

In [55]:
arr=np.arange(25)

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
len(arr)

25

In [60]:
ranarr.max()

49

In [61]:
ranarr.min()

7

In [63]:
ranarr.argmin()

3

In [65]:
np.random.randn(50).reshape(5,10)

array([[ 1.33741975, -0.03406673,  1.20566877, -2.0446301 ,  0.04705274,
        -1.17378064,  0.57624794, -2.19171265,  1.33446304, -0.71381174],
       [ 0.05961399, -0.35530311, -1.06864726, -1.39322184,  0.8706996 ,
         0.78237914,  1.39818005, -0.1209782 ,  1.89254658,  1.35622544],
       [ 1.59702509, -0.60532809, -0.6555317 ,  0.47838285, -1.22358009,
         0.00333589, -0.1326415 ,  0.4644575 ,  0.30566052, -0.69244047],
       [ 0.62331679,  1.50069655, -0.77253121, -0.32390142,  0.83570448,
         0.29437477, -1.3578295 ,  0.46783946, -1.48168496,  0.73766592],
       [-1.00427832, -0.47860308, -0.67689694, -1.6686461 ,  1.82442562,
        -2.02729751,  0.39453238, -0.39307353, -1.59587645,  0.18120497]])

In [66]:
np.random.randn(50).reshape(5,10).shape

(5, 10)

In [89]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
arr+arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [76]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
arr*arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [78]:
arr**3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

In [79]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [80]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

In [81]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [83]:
np.log(arr)

c:\users\vkp\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [84]:
np.max(arr)

8

In [85]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
arr[1:5]

array([[3, 4, 5],
       [6, 7, 8]])

In [93]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [100]:
arr1=np.arange(0,10)

In [104]:
arr1[1:5]=2

In [102]:
arr1[-1]=50

In [105]:
arr1

array([ 0,  2,  2,  2,  2,  5,  6,  7,  8, 50])

In [115]:
arr_2d=np.array(([0,2,7],[8,50,54],[45,43,22]))

In [120]:
arr_2d

array([[ 0,  2,  7],
       [ 8, 50, 54],
       [45, 43, 22]])

In [130]:
arr_2d[1:2,:2]

array([[ 8, 50]])

In [133]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [136]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [137]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [138]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
np.random.rand(25)

array([0.12383363, 0.94428959, 0.03332398, 0.6055505 , 0.75083274,
       0.52398946, 0.41795921, 0.66246613, 0.36649766, 0.48542863,
       0.19293959, 0.17805756, 0.36872236, 0.79717401, 0.16138831,
       0.11381808, 0.52036488, 0.44576083, 0.57255295, 0.25146265,
       0.64211983, 0.40061479, 0.41115347, 0.57905102, 0.07915527])

In [148]:
np.arange(0.0,1.00,0.01).reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [149]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [151]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [152]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [159]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])